### PR TITLE
Wasp cowboy bug

### PR DESCRIPTION
**Pull request by unbun**
- wasps use CharactorControllers now instead of RigidBodies
 - wasp recoil is a bit more exageratted, so their attack speed and recoil recovery might need adjustments
 - wasps shouldn't start riding the player if the player is too slow
 - prefab directory reorganized

### CODE REVIEW

**Comment by unbun** [comment]
There was a bug with npc's that i knew i would forget about if i didn't fix it now (npc's wouldn't let you un-pause if you were landed)

**Comment by brockfenbert** [comment]
This change fixed the recoil problem on level 1, however wasp interactions with the hive are kind of broken on level 3. I think this could be fine since as of now none of the wasps are in position to attack the hive on level 3, but that might change as we tweak the level more.

**Comment by brockfenbert** [comment]
wasp

Here is an example of what I saw with the wasp/hive, this wasp just kind of endlessly sat there doing nothing

**Comment by brockfenbert** [comment]
I was doing some more testing/ trying to fix teh bug, I was able to catch the wasp on level 3 (slightly different than how you catch before). 

I ran up to it then flew up at the slowest speed
catchWasp

I could not get the wasp to actually attack the hive any more

**Pull request merged**
